apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Ecommerce-Ritz-API
  description: "API service for ecommerce app"
  owner: ritesh.crazy04@gmail.com
spec:
  type: service
  lifecycle: production
  system: Ecommerce-Ritz
  owner: ritesh.crazy04@gmail.com
  providesApis:
    - Ecommerce-Ritz-API
  implementsApis:
    - Ecommerce-Ritz-API
  dependsOn:
    - Ecommerce-Ritz-API
  repository: https://github.com/ritesh12345/ecommerce_ritz
